name: Repository Dispatch
on:
  repository_dispatch:
    types: [update-repo]
jobs:
  setupEnvironment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Set NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git status
          git diff --name-only

  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo It worked! version ${{github.event.client_payload.version}}
