name: Repository Dispatch
on:
  repository_dispatch:
    types: [update-repo]
jobs:
  PublishToNPM:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Set NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Setup user on Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit changes
        run: |
          git commit -a -m "Update chroma-components dependency"

      - name: Create new version
        run: |
          npm version ${{github.event.client_payload.version}}

      - name: Set NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org"

      - name: Run Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: ${{ github.ref }}
